Neos:
  Neos:
    userInterface:
      translation:
        autoInclude:
          Psmb.CreateNodeButton:
            - Main
            - 'NodeTypes/*'
    fusion:
      autoInclude:
        Psmb.CreateNodeButton: true
    Ui:
      resources:
        javascript:
          'Psmb.CreateNodeButton:CreateNodeView':
            resource: resource://Psmb.CreateNodeButton/Public/JavaScript/CreateNodeView/Plugin.js
